function fig_hdl = new_evidence_build(tab)
% Initialize handles structure
handles = struct();
handles.addnewevidancetab =tab;
% Create all UI controls
build_gui();
handles.evidence_clip = '';
handles.fs = '';
handles.path = '';
handles.filename = '';% Update handles structure
set(handles.evidanceclipedit, 'Enable', 'off' );
set(handles.remarks, 'Enable', 'off' );
set(handles.Recording_date, 'Enable', 'off' );
set(handles.save, 'Enable', 'off' );
% Assign function output
fig_hdl = handles.addnewevidancetab;

%% ---------------------------------------------------------------------------
    function build_gui()
        % Creation of all uicontrols
        % --- PANELS -------------------------------------
        handles.evidancepanel = uipanel( ...
            'Parent', handles.addnewevidancetab, ...
            'Tag', 'evidancepanel', ...
            'UserData', zeros(1,0), ...
            'Units', 'normalized', ...
            'Position', [-0.002 -0.0144927536231884 1.002 1.01449275362319], ...
            'BackgroundColor', [1 1 1], ...
            'Title', '', ...
            'BorderType', 'none');
        
        handles.backbox = uipanel( ...
            'Parent', handles.evidancepanel, ...
            'Tag', 'backbox', ...
            'UserData', zeros(1,0), ...
            'Units', 'normalized', ...
            'Position', [0.0339321357285428 0.0659801297464048 0.922155688622754 0.908510638297872], ...
            'BackgroundColor', [1 1 1], ...
            'Title', '');
        
        % --- STATIC TEXTS -------------------------------------
        handles.text2 = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'text2', ...
            'Style', 'text', ...
            'Units', 'normalized', ...
            'Position', [0.0538735414531788 0.872760306536075 0.298850574712644 0.0609756097560976], ...
            'FontSize', 10, ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Case No *', ...
            'HorizontalAlignment', 'left');
        
        handles.text7 = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'text7', ...
            'Style', 'text', ...
            'Units', 'normalized', ...
            'Position', [0.0560859308337098 0.750838331586689 0.298850574712644 0.0609756097560976], ...
            'FontSize', 10, ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Evidence Voice Clip *', ...
            'HorizontalAlignment', 'left');
        
        handles.text8 = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'text8', ...
            'Style', 'text', ...
            'Units', 'normalized', ...
            'Position', [0.0553270869546784 0.605557329926541 0.41747572815534 0.0744416873449131], ...
            'FontSize', 10, ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Date of the voice recording', ...
            'HorizontalAlignment', 'left');
        
        handles.text100 = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'text100', ...
            'Style', 'text', ...
            'Units', 'normalized', ...
            'Position', [0.056768558951965 0.497524752475248 0.299126637554585 0.051980198019802], ...
            'FontSize', 10, ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Voice Clip Details', ...
            'HorizontalAlignment', 'left');
        
        % --- PUSHBUTTONS -------------------------------------
        handles.save = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'save', ...
            'Style', 'pushbutton', ...
            'Units', 'normalized', ...
            'Position', [0.510917030567686 0.131188118811881 0.231441048034934 0.0866336633663366], ...
            'FontSize', 12, ...
            'String', 'Save', ...
            'Enable', 'off', ...
            'Callback', @save_Callback);
        
        handles.reset = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'reset', ...
            'Style', 'pushbutton', ...
            'Units', 'normalized', ...
            'Position', [0.14410480349345 0.133663366336634 0.231441048034934 0.0866336633663366], ...
            'FontSize', 12, ...
            'String', 'Reset', ...
            'Callback', @reset_Callback);
        
        handles.Browsepushbutton = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'Browsepushbutton', ...
            'Style', 'pushbutton', ...
            'Units', 'normalized', ...
            'Position', [0.838427947598252 0.764851485148515 0.137554585152838 0.0569306930693069], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Browse', ...
            'Callback', @Browsepushbutton_Callback);
        
        handles.Loadpushbutton = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'Loadpushbutton', ...
            'Style', 'pushbutton', ...
            'Units', 'normalized', ...
            'Position', [0.836244541484716 0.883663366336634 0.137554585152838 0.0569306930693069], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Check', ...
            'Callback', @Loadpushbutton_Callback);
        
        % --- EDIT TEXTS -------------------------------------
        handles.ID = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'ID', ...
            'Style', 'edit', ...
            'Units', 'normalized', ...
            'Position', [0.427947598253275 0.881188118811881 0.399563318777293 0.0594059405940594], ...
            'FontSize', 10, ...
            'BackgroundColor', [1 1 1], ...
            'String', '', ...
            'HorizontalAlignment', 'left', ...
            'Callback', @ID_Callback, ...
            'CreateFcn', @ID_CreateFcn);
        
        handles.remarks = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'remarks', ...
            'Style', 'edit', ...
            'Units', 'normalized', ...
            'Position', [0.427947598253275 0.28960396039604 0.399563318777293 0.264851485148515], ...
            'FontSize', 10, ...
            'BackgroundColor', [1 1 1], ...
            'Enable', 'off', ...
            'HorizontalAlignment', 'left', ...
            'Max', 2, ...
            'Callback', @remarks_Callback, ...
            'CreateFcn', @remarks_CreateFcn);
        
        handles.evidanceclipedit = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'evidanceclipedit', ...
            'Style', 'edit', ...
            'Units', 'normalized', ...
            'Position', [0.427947598253275 0.75990099009901 0.399563318777293 0.0594059405940594], ...
            'FontSize', 10, ...
            'BackgroundColor', [1 1 1], ...
            'String', '', ...
            'Enable', 'off', ...
            'HorizontalAlignment', 'left', ...
            'Callback', @evidanceclipedit_Callback, ...
            'CreateFcn', @evidanceclipedit_CreateFcn);
        
        % --- POPUP MENU -------------------------------------
        handles.Recording_date = uicontrol( ...
            'Parent', handles.backbox, ...
            'Tag', 'Recording_date', ...
            'Style', 'popupmenu', ...
            'Units', 'normalized', ...
            'Position', [0.427947598253275 0.606435643564356 0.399563318777293 0.0767326732673267], ...
            'FontSize', 10, ...
            'BackgroundColor', [1 1 1], ...
            'String', 'select', ...
            'Enable', 'off', ...
            'Callback', @Recording_date_Callback, ...
            'CreateFcn', @Recording_date_CreateFcn);
        
        
    end

%% ---------------------------------------------------------------------------
    function figure1_DeleteFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function save_Callback(hObject,evendata) %#ok<INUSD>
        ID = get(handles.ID,'String');
        recording_date = get(handles.Recording_date,'String');
        remarks = get(handles.remarks,'String');
        clip_length = length(handles.evidence_clip)/handles.fs;
        
        if ((strcmp(ID,'') == 0) && (strcmp(handles.path,'') == 0) )
            msgbox('This will take time. Please wait..');
            M = HashStore();
            result= M.add_evidence(ID,remarks,recording_date,handles.evidence_clip,handles.fs,handles.path,handles.filename,clip_length);
            msgbox(result,'Saving new evidance');
            
            path = 'C:\Forensic_Audio_workspace\cases';
            pathofcase  = [path, '\', ID,'\Evidence'];
            
            mkdir(pathofcase);
            
            audiowrite([pathofcase,'\',handles.filename,'.wav'],handles.evidence_clip,handles.fs);
            
            
        else
            errordlg('Enter * marked fields','File Error');
        end
    end

%% ---------------------------------------------------------------------------
    function reset_Callback(hObject,evendata) %#ok<INUSD>
        set(handles.ID,'String','');
        set(handles.evidanceclipedit,'String','');
        set(handles.remarks,'String','');
        set(handles.Recording_date, 'String', 'select');
        set(handles.evidanceclipedit, 'Enable', 'off' );
        set(handles.remarks, 'Enable', 'off' );
        set(handles.Recording_date, 'Enable', 'off' );
        set(handles.save, 'Enable', 'off' );
    end

%% ---------------------------------------------------------------------------
    function Browsepushbutton_Callback(hObject,evendata) %#ok<INUSD>
        [filename, pathname] = uigetfile( ...
            {'*.wav', 'All WAV-Files (*.wav)'; ...
            '*.*','All Files (*.*)'}, ...
            'Select Evidance Clip');
        % If "Cancel" is selected then return
        if isequal([filename,pathname],[0,0])
            return
            % Otherwise construct the fullfilename and Check and load the file.
        else
            File = fullfile(pathname,filename);
            % if the MAT-file is not valid, do not save the name
            if exist(File,'file') == 2
                [evidence_clip, fs] = audioread(File);
                handles.evidence_clip = evidence_clip;
                handles.fs = fs;
                handles.path = File;
                [a b] = fileparts(filename);
                handles.filename = b;
            end
            set(handles.evidanceclipedit, 'String', [File]);
        end
    end

%% ---------------------------------------------------------------------------
    function Loadpushbutton_Callback(hObject,evendata) %#ok<INUSD>
        path = 'C:\Forensic_Audio_workspace\cases';
        pathofcase  = [path, '\', get(handles.ID,'String')];
        if( strcmp(get(handles.ID,'String'),'')==0)
            if(exist(pathofcase,'dir'))
                display('folder found');
                msgbox('Case Found');
                set(handles.evidanceclipedit, 'Enable', 'on' );
                set(handles.remarks, 'Enable', 'on' );
                set(handles.Recording_date, 'Enable', 'on' );
                set(handles.save, 'Enable', 'on' );
            else
                set(handles.evidanceclipedit, 'Enable', 'off' );
                set(handles.remarks, 'Enable', 'off' );
                set(handles.Recording_date, 'Enable', 'off' );
                set(handles.save, 'Enable', 'off' );
                errordlg('Case File Not Found. To create new case go to ''New case'' tab');
            end
        else
         errordlg('Enter Case Number');   
        end
        
    end

%% ---------------------------------------------------------------------------
    function ID_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function ID_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function remarks_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function remarks_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function evidanceclipedit_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function evidanceclipedit_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function Recording_date_Callback(hObject,evendata) %#ok<INUSD>
        uicalendar('SelectionType', 1, 'DestinationUI',handles.Recording_date);
    end

%% ---------------------------------------------------------------------------
    function Recording_date_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

end
