function fig_hdl = new_suspect_build(tab)
% Initialize handles structure
handles = struct();
handles.addnewsuspecttab =tab;
% Create all UI controls
build_gui();

handles.suspect_clip = '';
handles.fs = '';
handles.path = '';
handles.filename = '';% Update handles structure
set(handles.Name, 'Enable', 'off' );
set(handles.NIC, 'Enable', 'off' );
set(handles.birthday, 'Enable', 'off' );
set(handles.Address, 'Enable', 'off' );
set(handles.Recording_date, 'Enable', 'off' );
set(handles.save, 'Enable', 'off' );
set(handles.Suspect, 'Enable', 'off' );
set(handles.remarks, 'Enable', 'off' );
set(handles.gender, 'Enable', 'off' );
set(handles.mismatchedit, 'Enable', 'off' );
set(handles.verificationpopupmenu, 'Enable', 'off' );
% Assign function output
fig_hdl = handles.addnewsuspecttab;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

	% --- PANELS -------------------------------------
		handles.uipanel3 = uipanel( ...
			'Parent', handles.addnewsuspecttab, ...
			'Tag', 'uipanel3', ...
			'UserData', zeros(1,0), ...
			'Units', 'normalized', ...
			'Position', [0.0151515151515152 -0.00165289256198347 0.979166666666667 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', '', ...
			'BorderType', 'none');

		handles.backuipanel = uipanel( ...
			'Parent', handles.uipanel3, ...
			'Tag', 'backuipanel', ...
			'Units', 'normalized', ...
			'Position', [0.0809248554913295 0.0406779661016949 0.845857418111753 0.933898305084746], ...
			'BackgroundColor', [1 1 1], ...
			'Title', '');

		% --- STATIC TEXTS -------------------------------------
		handles.text1 = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'text1', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0459770114942529 0.863387978142076 0.344827586206897 0.0455373406193078], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Full Name *', ...
			'HorizontalAlignment', 'left', ...
			'CreateFcn', @text1_CreateFcn);

		handles.text2 = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'text2', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0459770114942529 0.792349726775956 0.344827586206897 0.0455373406193078], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'NIC no: ', ...
			'HorizontalAlignment', 'left');

		handles.text3 = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'text3', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0459770114942529 0.730418943533698 0.344827586206897 0.0455373406193078], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Home Address', ...
			'HorizontalAlignment', 'left');

		handles.text4 = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'text4', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0459770114942529 0.657559198542805 0.344827586206897 0.0455373406193078], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Birthday', ...
			'HorizontalAlignment', 'left');

		handles.text5 = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'text5', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0459770114942529 0.577413479052823 0.344827586206897 0.0455373406193078], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Gender *', ...
			'HorizontalAlignment', 'left');

		handles.text7 = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'text7', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0459770114942529 0.508196721311475 0.344827586206897 0.0455373406193078], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Suspect Voice Clip *', ...
			'HorizontalAlignment', 'left');

		handles.text8 = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'text8', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0459770114942529 0.429872495446266 0.388505747126437 0.0528233151183971], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Date of the voice recording', ...
			'HorizontalAlignment', 'left');

		handles.text9 = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'text9', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0413793103448276 0.202185792349727 0.344827586206897 0.0455373406193078], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Other Remarks', ...
			'HorizontalAlignment', 'left');

		handles.text10 = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'text10', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0436781609195402 0.934426229508197 0.344827586206897 0.0455373406193078], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Case ID *', ...
			'HorizontalAlignment', 'left');

		handles.text11 = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'text11', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0482758620689655 0.36247723132969 0.388505747126437 0.0528233151183971], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Verification Option *', ...
			'HorizontalAlignment', 'left');

		handles.text12 = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'text12', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0482758620689655 0.29143897996357 0.344827586206897 0.0455373406193078], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Mismatch Conditions *', ...
			'HorizontalAlignment', 'left');

		% --- PUSHBUTTONS -------------------------------------
		handles.save = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'save', ...
			'Style', 'pushbutton', ...
			'Units', 'normalized', ...
			'Position', [0.501149425287356 0.0255009107468124 0.232183908045977 0.0655737704918033], ...
			'FontSize', 14, ...
			'String', 'Save', ...
			'Enable', 'off', ...
			'Callback', @save_Callback);

		handles.reset = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'reset', ...
			'Style', 'pushbutton', ...
			'Units', 'normalized', ...
			'Position', [0.154022988505747 0.0255009107468124 0.232183908045977 0.0655737704918033], ...
			'FontSize', 14, ...
			'String', 'Reset', ...
			'Callback', @reset_Callback);

		handles.loadpushbutton = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'loadpushbutton', ...
			'Style', 'pushbutton', ...
			'Units', 'normalized', ...
            'Position', [0.859695787210321 0.938085958427087 0.119540229885057 0.0418943533697632], ...
            'BackgroundColor', [1 1 1], ...
            'String', 'Check', ...
			'Callback', @loadpushbutton_Callback);

		% --- EDIT TEXTS -------------------------------------
		handles.Name = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'Name', ...
			'UserData', zeros(1,0), ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.452655889145497 0.869485294117647 0.390300230946882 0.0459558823529412], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'Enable', 'off', ...
			'HorizontalAlignment', 'left', ...
			'Callback', @Name_Callback, ...
			'CreateFcn', @Name_CreateFcn);

		handles.NIC = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'NIC', ...
			'UserData', zeros(1,0), ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.452655889145497 0.797794117647059 0.390300230946882 0.0459558823529412], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'Enable', 'off', ...
			'HorizontalAlignment', 'left', ...
			'Callback', @NIC_Callback, ...
			'CreateFcn', @NIC_CreateFcn);

		handles.Address = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'Address', ...
			'UserData', zeros(1,0), ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.452655889145497 0.733455882352941 0.390300230946882 0.0459558823529412], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'Enable', 'off', ...
			'HorizontalAlignment', 'left', ...
			'Callback', @Address_Callback, ...
			'CreateFcn', @Address_CreateFcn);

		handles.remarks = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'remarks', ...
			'UserData', zeros(1,0), ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.452655889145497 0.159926470588235 0.501154734411085 0.0808823529411765], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'Enable', 'off', ...
			'HorizontalAlignment', 'left', ...
			'Max', 2, ...
			'Callback', @remarks_Callback, ...
			'CreateFcn', @remarks_CreateFcn);

		handles.CaseIDedit = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'CaseIDedit', ...
			'UserData', zeros(1,0), ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.452655889145497 0.933823529411765 0.390300230946882 0.0459558823529412], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'HorizontalAlignment', 'left', ...
			'Callback', @CaseIDedit_Callback, ...
			'CreateFcn', @CaseIDedit_CreateFcn);

		handles.mismatchedit = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'mismatchedit', ...
			'UserData', zeros(1,0), ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.452655889145497 0.272058823529412 0.501154734411085 0.0808823529411765], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'Enable', 'off', ...
			'HorizontalAlignment', 'left', ...
			'Max', 2, ...
			'Callback', @mismatchedit_Callback, ...
			'CreateFcn', @mismatchedit_CreateFcn);

		% --- POPUP MENU -------------------------------------
		handles.birthday = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'birthday', ...
			'UserData', zeros(1,0), ...
			'Style', 'popupmenu', ...
			'Units', 'normalized', ...
			'Position', [0.452655889145497 0.658088235294118 0.390300230946882 0.0459558823529412], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Select', ...
			'Enable', 'off', ...
			'Callback', @birthday_Callback, ...
			'CreateFcn', @birthday_CreateFcn);

		handles.gender = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'gender', ...
			'UserData', zeros(1,0), ...
			'Style', 'popupmenu', ...
			'Units', 'normalized', ...
			'Position', [0.452655889145497 0.577205882352941 0.390300230946882 0.0459558823529412], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', {'Female','Male'}, ...
			'Enable', 'off', ...
			'Callback', @gender_Callback, ...
			'CreateFcn', @gender_CreateFcn);

		handles.Suspect = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'Suspect', ...
			'UserData', zeros(1,0), ...
			'Style', 'popupmenu', ...
			'Units', 'normalized', ...
			'Position', [0.452655889145497 0.507352941176471 0.390300230946882 0.0459558823529412], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Select', ...
			'Enable', 'off', ...
			'Callback', @Suspect_Callback, ...
			'CreateFcn', @Suspect_CreateFcn);

		handles.Recording_date = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'Recording_date', ...
			'UserData', zeros(1,0), ...
			'Style', 'popupmenu', ...
			'Units', 'normalized', ...
			'Position', [0.452655889145497 0.4375 0.390300230946882 0.0459558823529412], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Select', ...
			'Enable', 'off', ...
			'Callback', @Recording_date_Callback, ...
			'CreateFcn', @Recording_date_CreateFcn);

		handles.verificationpopupmenu = uicontrol( ...
			'Parent', handles.backuipanel, ...
			'Tag', 'verificationpopupmenu', ...
			'UserData', zeros(1,0), ...
			'Style', 'popupmenu', ...
			'Units', 'normalized', ...
			'Position', [0.452655889145497 0.369485294117647 0.390300230946882 0.0459558823529412], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', {'Option1:(Basic matching)','Option2:(UBM)','Option3:(Cohort)'}, ...
			'Enable', 'off', ...
			'Callback', @verificationpopupmenu_Callback, ...
			'CreateFcn', @verificationpopupmenu_CreateFcn);


	end

%% ---------------------------------------------------------------------------
	function figure1_DeleteFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function text1_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function save_Callback(hObject,evendata) %#ok<INUSD>
        ID = get(handles.CaseIDedit,'String');
        name = get(handles.Name,'String');
        NIC = get(handles.NIC,'String');
        bday = get(handles.birthday,'String');
        gender = get(handles.gender,'Value');
        address = get(handles.Address,'String');
        recording_date = get(handles.Recording_date,'String');
        mismatch= get(handles.mismatchedit,'String');
        remarks= get(handles.remarks,'String');
        option = get(handles.verificationpopupmenu,'Value');
        clip_length = length(handles.suspect_clip)/handles.fs;
        
        if ((strcmp(ID,'') == 0) && (strcmp(mismatch,'') == 0) &&(strcmp(name,'') == 0) && (strcmp(handles.path,'') == 0) ) 
            display(handles.filename);
            msgbox('This will take time. Please wait..');
            M = HashStore();
            result= M.add_suspect(option,ID,name,NIC,bday,gender,address,recording_date,mismatch, remarks,handles.suspect_clip,handles.fs,handles.path,handles.filename,clip_length);
            msgbox(result,'Saving new Suspect');
%             
            path = ['C:\Forensic_Audio_workspace\cases\',ID];
            mkdir(path);
            pathofcase  = [path,'\Suspects\Option',num2str(option)];
            mkdir(pathofcase);
            audiowrite([pathofcase,'\',handles.filename,'.wav'],handles.suspect_clip,handles.fs);
        else
            errordlg('* marked feilds must be fill','File Error');
        end
	end

%% ---------------------------------------------------------------------------
	function reset_Callback(hObject,evendata) %#ok<INUSD>
        set(handles.CaseIDedit,'String','');
        set(handles.Suspect, 'String', 'select');
        set(handles.Name,'String','');
        set(handles.birthday,'String','select');
        set(handles.NIC,'String','');
        set(handles.remarks,'String','');
        set(handles.Address,'String','');
        set(handles.Recording_date,'String','select');
        handles.suspect_clip = '';
        handles.fs = '';
        handles.path = '';
        handles.filename = '';
        set(handles.Name, 'Enable', 'off' );
        set(handles.NIC, 'Enable', 'off' );
        set(handles.birthday, 'Enable', 'off' );
        set(handles.Address, 'Enable', 'off' );
        set(handles.Recording_date, 'Enable', 'off' );
        set(handles.save, 'Enable', 'off' );
        set(handles.Suspect, 'Enable', 'off' );
        set(handles.remarks, 'Enable', 'off' )
        set(handles.gender, 'Enable', 'off' );
        set(handles.mismatchedit, 'Enable', 'off' );
        set(handles.verificationpopupmenu, 'Enable', 'off' );
	end

%% ---------------------------------------------------------------------------
	function loadpushbutton_Callback(hObject,evendata) %#ok<INUSD>
        path = 'C:\Forensic_Audio_workspace\cases';
        pathofcase  = [path, '\', get(handles.CaseIDedit,'String')];
        if( strcmp(get(handles.CaseIDedit,'String'),'')==0)
            if(exist(pathofcase,'dir'))
                display('folder found');
                msgbox('Case Found');
                set(handles.Name, 'Enable', 'on' );
                set(handles.NIC, 'Enable', 'on' );
                set(handles.birthday, 'Enable', 'on' );
                set(handles.Address, 'Enable', 'on' );
                set(handles.Recording_date, 'Enable', 'on' );
                set(handles.save, 'Enable', 'on' );
                set(handles.Suspect, 'Enable', 'on' );
                set(handles.gender, 'Enable', 'on' );
                set(handles.remarks, 'Enable', 'on' );
                set(handles.mismatchedit, 'Enable', 'on' );
                set(handles.verificationpopupmenu, 'Enable', 'on' );
            else
                errordlg('Case File Not Found. To create new case go to ''New case'' tab');
            end
        else
            errordlg('Enter Case Number');
        end
        
	end

%% ---------------------------------------------------------------------------
	function Name_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function Name_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function NIC_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function NIC_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function Address_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function Address_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function remarks_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function remarks_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function CaseIDedit_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function CaseIDedit_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function mismatchedit_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function mismatchedit_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function birthday_Callback(hObject,evendata) %#ok<INUSD>
        uicalendar('SelectionType', 1, 'DestinationUI',handles.birthday);
	end

%% ---------------------------------------------------------------------------
	function birthday_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function gender_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function gender_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function Suspect_Callback(hObject,evendata) %#ok<INUSD>
        [filename, pathname] = uigetfile( ...
            {'*.wav', 'All WAV-Files (*.wav)'; ...
            '*.*','All Files (*.*)'}, ...
            'Select Evidance Clip');
        % If "Cancel" is selected then return
        if isequal([filename,pathname],[0,0])
            return
            % Otherwise construct the fullfilename and Check and load the file.
        else
            File = fullfile(pathname,filename);
            % if the MAT-file is not valid, do not save the name
            if exist(File,'file') == 2
                [suspect_clip suspect_fs] = audioread(File);
                handles.suspect_clip = suspect_clip;
                handles.fs = suspect_fs;
                handles.path = File;
                [a b] = fileparts(filename);
                handles.filename = b;
            end
            set(handles.Suspect, 'String', [File]);
        end
	end

%% ---------------------------------------------------------------------------
	function Suspect_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function Recording_date_Callback(hObject,evendata) %#ok<INUSD>
        uicalendar('SelectionType', 1, 'DestinationUI',handles.Recording_date);
	end

%% ---------------------------------------------------------------------------
	function Recording_date_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function verificationpopupmenu_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function verificationpopupmenu_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

end
