function fig_hdl = new_case_build(tab)

handles = struct();
handles.addnewcasetab =tab;
% Create all UI controls
build_gui();
handles.evidence_clip = '';
handles.fs = '';
handles.path = '';
handles.filename = '';
% Assign function output
fig_hdl = handles.addnewcasetab;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

% --- PANELS -------------------------------------
		handles.uipanel3 = uipanel( ...
			'Parent', handles.addnewcasetab, ...
			'Tag', 'uipanel3', ...
			'UserData', zeros(1,0), ...
			'Units', 'normalized', ...
			'Position', [-0.00202020202020202 -0.0023696682464455 1.01212121212121 1.00236966824645], ...
			'BackgroundColor', [1 1 1], ...
			'Title', '', ...
			'BorderType', 'none');

		handles.uipanel4 = uipanel( ...
			'Parent', handles.uipanel3, ...
			'Tag', 'uipanel4', ...
			'UserData', zeros(1,0), ...
			'Units', 'normalized', ...
			'Position', [0.0379241516966068 0.0570719602977667 0.914171656686627 0.930521091811414], ...
			'BackgroundColor', [1 1 1], ...
			'Title', '');

		% --- STATIC TEXTS -------------------------------------
		handles.text11 = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'text11', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0814977973568286 0.560906515580737 0.299559471365639 0.0623229461756374], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'ID No of the incharge', ...
			'HorizontalAlignment', 'left');

		handles.text10 = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'text10', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0814977973568286 0.30028328611898 0.299559471365639 0.0623229461756374], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Case Details *', ...
			'HorizontalAlignment', 'left');

		handles.text9 = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'text9', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0814977973568286 0.422096317280453 0.29295154185022 0.0623229461756374], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Date of the case', ...
			'HorizontalAlignment', 'left');

		handles.text8 = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'text8', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0814977973568286 0.679886685552408 0.299559471365639 0.0623229461756374], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Name of the incharge', ...
			'HorizontalAlignment', 'left');

		handles.text7 = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'text7', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0814977973568286 0.926345609065156 0.299559471365639 0.0623229461756374], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Case No *', ...
			'HorizontalAlignment', 'left');

		handles.text6 = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'text6', ...
			'UserData', zeros(1,0), ...
			'Style', 'text', ...
			'Units', 'normalized', ...
			'Position', [0.0814977973568286 0.804532577903683 0.299559471365639 0.0623229461756374], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Case Name *', ...
			'HorizontalAlignment', 'left');

		% --- PUSHBUTTONS -------------------------------------
		handles.resetpushbutton = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'resetpushbutton', ...
			'UserData', zeros(1,0), ...
			'Style', 'pushbutton', ...
			'Units', 'normalized', ...
			'Position', [0.185022026431718 0.0396600566572238 0.231277533039648 0.0878186968838527], ...
			'FontSize', 12, ...
			'String', 'Reset', ...
			'CData', zeros(1,0), ...
			'Callback', @resetpushbutton_Callback);

		handles.savepushbutton = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'savepushbutton', ...
			'UserData', zeros(1,0), ...
			'Style', 'pushbutton', ...
			'Units', 'normalized', ...
			'Position', [0.552863436123349 0.0424929178470255 0.231277533039648 0.0878186968838527], ...
			'FontSize', 12, ...
			'String', 'Save', ...
			'CData', zeros(1,0), ...
			'Callback', @savepushbutton_Callback);

		% --- EDIT TEXTS -------------------------------------
		handles.IDnoedit = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'IDnoedit', ...
			'UserData', zeros(1,0), ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.400881057268725 0.575070821529745 0.5 0.07], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'HorizontalAlignment', 'left', ...
			'Callback', @IDnoedit_Callback, ...
			'CreateFcn', @IDnoedit_CreateFcn);

		handles.nameofinchargeedit = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'nameofinchargeedit', ...
			'UserData', zeros(1,0), ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.400881057268725 0.68271954674221 0.5 0.07], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'HorizontalAlignment', 'left', ...
			'Callback', @nameofinchargeedit_Callback, ...
			'CreateFcn', @nameofinchargeedit_CreateFcn);

		handles.detailsedit = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'detailsedit', ...
			'UserData', zeros(1,0), ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.400881057268725 0.203966005665722 0.5 0.164305949008499], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'HorizontalAlignment', 'left', ...
			'Max', 2, ...
			'Callback', @detailsedit_Callback, ...
			'CreateFcn', @detailsedit_CreateFcn);

		handles.casenoedit = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'casenoedit', ...
			'UserData', zeros(1,0), ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.400881057268724 0.923512747875354 0.5 0.0708215297450425], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'HorizontalAlignment', 'left', ...
			'Callback', @casenoedit_Callback, ...
			'CreateFcn', @casenoedit_CreateFcn);

		handles.casenameedit = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'casenameedit', ...
			'UserData', zeros(1,0), ...
			'Style', 'edit', ...
			'Units', 'normalized', ...
			'Position', [0.400881057268725 0.810198300283286 0.5 0.07], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'HorizontalAlignment', 'left', ...
			'Callback', @casenameedit_Callback, ...
			'CreateFcn', @casenameedit_CreateFcn);

		% --- POPUP MENU -------------------------------------
		handles.datepopupmenu = uicontrol( ...
			'Parent', handles.uipanel4, ...
			'Tag', 'datepopupmenu', ...
			'UserData', zeros(1,0), ...
			'Style', 'popupmenu', ...
			'Units', 'normalized', ...
			'Position', [0.400881057268725 0.413597733711048 0.5 0.0764872521246459], ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'select', ...
			'Callback', @datepopupmenu_Callback, ...
			'CreateFcn', @datepopupmenu_CreateFcn);


	end

%% ---------------------------------------------------------------------------
	function resetpushbutton_Callback(hObject,evendata) %#ok<INUSD>
        set(handles.datepopupmenu, 'String', 'select');
        set(handles.detailsedit,'String','');
        set(handles.casenameedit,'String','');
        set(handles.casenoedit,'String','');
        set(handles.nameofinchargeedit,'String','');
        set(handles.IDnoedit,'String','');
	end

%% ---------------------------------------------------------------------------
	function savepushbutton_Callback(hObject,evendata) %#ok<INUSD>
        name = get(handles.casenameedit,'String');
        ID = get(handles.casenoedit,'String');
        Date = get(handles.datepopupmenu,'String');
        officer_name = get(handles.nameofinchargeedit,'String');
        officer_id = get(handles.IDnoedit,'String');
        description = get(handles.detailsedit,'String');
        
        if ((strcmp(name,'') == 0) && (strcmp(ID,'') == 0) && (strcmp(description,'') == 0) )
            
            M = HashStore();
            result= M.add_case(ID,name,Date,officer_name,officer_id,description)
            msgbox(result,'Saving new case');
            
            path = 'C:\Forensic_Audio_workspace\cases';
            pathofcase  = [path, '\', ID];
            if(exist(pathofcase,'dir'))
                display('folder found');
            else
                mkdir(pathofcase);
            end
            
        else
            errordlg('Enter * marked fields','File Error');
        end
	end

%% ---------------------------------------------------------------------------
	function IDnoedit_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function IDnoedit_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function nameofinchargeedit_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function nameofinchargeedit_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function detailsedit_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function detailsedit_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function casenoedit_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function casenoedit_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function casenameedit_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function casenameedit_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function datepopupmenu_Callback(hObject,evendata) %#ok<INUSD>
        uicalendar('SelectionType', 1, 'DestinationUI',handles.datepopupmenu);
	end

%% ---------------------------------------------------------------------------
	function datepopupmenu_CreateFcn(hObject,evendata) %#ok<INUSD>

	end

end
